# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opright', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=50)),
                ('post_date', models.DateTimeField()),
                ('post_comfirmed', models.BooleanField()),
                ('post_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opright.Participant')),
                ('post_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opright.Task')),
            ],
        ),
    ]
