# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opright', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='post_comfirmed',
            field=models.NullBooleanField(),
        ),
    ]
